name: Host Service CI
on:
  push:
    branches:
      - 'main'
    paths:
      - '*.js'
jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps: 
    - name: 1.Checkout
      uses: actions/checkout@v3

    - name: 2.Login to DockerHub 
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: 2.5 Buildx Setting
      uses: docker/setup-buildx-action@v2

    - name: 3. Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
       push: true
       tags: sorim/hostservice:${{ github.sha }} #절대 latest 쓰지 말것
  updateYaml:
    runs-on: ubuntu-latest
    needs: buildImage #앞에가 성공해야 이걸 성공할수 있다는 조건걸어둠
    steps:
      - name: 1.Checkout
        uses: actions/checkout@v3
        with:
          repository: 'sorim0418/hostsvc-cd'
          token: ${{ secrets.GH_TOKEN }}
      - name: 2. Change Docker Tag
        run: |
          sed -i "s/image: sorim\/node-app:.*/images: sorim\/node-app:${{ github.sha }}/g" hostservice-deploy.yml
          git config --global user.email "sorim09010418@gmail.com"
          git config --global user.name "sorim"
          git commit -am "triggered by github action yeah!!!"
          git push origin main
