name: Host Service CI
on:
  push:
    branches:
      - 'main'
    paths:
      - '*.js'
jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps: 
    - name: 1.Checkout
      uses: actions/checkout@v3

    - name: 2.Login to DockerHub 
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: 2.5 Buildx Setting
      uses: docker/setup-buildx-action@v2
      
    - name: 3. Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
       push: true
       tags: sorim/hostservice:${{ github.sha }} #절대 latest 쓰지 말것
  updateYaml:
    runs-on: ubuntu-latest
    steps:
      - name: 1.Checkout
        uses: actions/checkout@v3
        with:
          repository: 'sorim0418/hostsvc-cd'

